var searchData=
[
  ['vddmu_0',['Vddmu',['../classVIMP_1_1VIMPOptimizerFactorizedBase.html#af3c4f74981cf22262b1c57dd4751420c',1,'VIMP::VIMPOptimizerFactorizedBase']]],
  ['vdmu_1',['Vdmu',['../classVIMP_1_1VIMPOptimizerFactorizedBase.html#a92a0a6a1a0bf0ebfab181cf47db15f34',1,'VIMP::VIMPOptimizerFactorizedBase']]],
  ['vec_5ffactor_5foptimizers_5f_2',['vec_factor_optimizers_',['../classVIMP_1_1VIMPOptimizerGH.html#aa0475e770fd002858b29da8fcb629bcd',1,'VIMP::VIMPOptimizerGH']]],
  ['vimpoptimizer_3',['VIMPOptimizer',['../classVIMP_1_1VIMPOptimizer.html',1,'VIMP::VIMPOptimizer&lt; Function, costClass, Args &gt;'],['../classVIMP_1_1VIMPOptimizer.html#a953bc25a5c64d49cb8b27132925bfb71',1,'VIMP::VIMPOptimizer::VIMPOptimizer()']]],
  ['vimpoptimizerfactorizedbase_4',['VIMPOptimizerFactorizedBase',['../classVIMP_1_1VIMPOptimizerFactorizedBase.html',1,'VIMP::VIMPOptimizerFactorizedBase'],['../classVIMP_1_1VIMPOptimizerFactorizedBase.html#a364c23b8d135057fec199488c5a57f33',1,'VIMP::VIMPOptimizerFactorizedBase::VIMPOptimizerFactorizedBase()']]],
  ['vimpoptimizerfactorizedgausshermite_5',['VIMPOptimizerFactorizedGaussHermite',['../classVIMP_1_1VIMPOptimizerFactorizedGaussHermite.html',1,'VIMP::VIMPOptimizerFactorizedGaussHermite&lt; Function, CostClass &gt;'],['../classVIMP_1_1VIMPOptimizerFactorizedGaussHermite.html#a6639c002dcdbb690083a18531baa0103',1,'VIMP::VIMPOptimizerFactorizedGaussHermite::VIMPOptimizerFactorizedGaussHermite(const int &amp;dimension, const Function &amp;function_, const CostClass &amp;cost_class_, const MatrixXd &amp;Pk_)'],['../classVIMP_1_1VIMPOptimizerFactorizedGaussHermite.html#a6639c002dcdbb690083a18531baa0103',1,'VIMP::VIMPOptimizerFactorizedGaussHermite::VIMPOptimizerFactorizedGaussHermite(const int &amp;dimension, const Function &amp;function_, const CostClass &amp;cost_class_, const MatrixXd &amp;Pk_)']]],
  ['vimpoptimizerfactorizedtwoclassgh_6',['VIMPOptimizerFactorizedTwoClassGH',['../classVIMP_1_1VIMPOptimizerFactorizedTwoClassGH.html',1,'VIMP::VIMPOptimizerFactorizedTwoClassGH&lt; Function, CostClass, CostClass1 &gt;'],['../classVIMP_1_1VIMPOptimizerFactorizedTwoClassGH.html#a27de1598d1f1b05a9f321d8a986893f5',1,'VIMP::VIMPOptimizerFactorizedTwoClassGH::VIMPOptimizerFactorizedTwoClassGH()']]],
  ['vimpoptimizergh_7',['VIMPOptimizerGH',['../classVIMP_1_1VIMPOptimizerGH.html',1,'VIMP::VIMPOptimizerGH&lt; FactorizedOptimizer &gt;'],['../classVIMP_1_1VIMPOptimizerGH.html#a725cdac4e1c5203e19e449eefba9848e',1,'VIMP::VIMPOptimizerGH::VIMPOptimizerGH(const vector&lt; FactorizedOptimizer &gt; &amp;_vec_fact_optimizers)'],['../classVIMP_1_1VIMPOptimizerGH.html#a7e89373e60acc0d3db2839f503554e63',1,'VIMP::VIMPOptimizerGH::VIMPOptimizerGH(const vector&lt; std::shared_ptr&lt; FactorizedOptimizer &gt; &gt; &amp;_vec_fact_optimizers, int niters=10)']]],
  ['vimpresults_8',['VIMPResults',['../structVIMP_1_1VIMPResults.html',1,'VIMP::VIMPResults'],['../structVIMP_1_1VIMPResults.html#aac432d1503fa297b966e5a79b480c0d7',1,'VIMP::VIMPResults::VIMPResults()']]]
];
