total_time:          4.0
n_states:            20
map_name:            map_bookshelf
coeff_Qc:            1.0
GH_deg:              3
sig_obs:             20.5
eps_sdf:             0.2
radius:              0.0
step_size:           0.7
init_precision_factor: 10000.0
boundary_penalties:  10000.0
temperature:         0.01
high_temperature:    0.2
low_temp_iterations: 20
stop_err:            1e-5
max_iterations:      30
max_n_backtracking:  5
sdf_file:            /home/hzyu/git/VIMP/vimp/maps/WAM/WAMDeskDataset.bin

start_pos: [-0.8, -1.70, 1.64, 1.29, 1.1, -0.106, 2.2]
goal_pos:  [-0.0,  0.94, 0.00, 1.6, 0.0, -0.919, 1.55]

saving_prefix: scripts/hardware_experiment/Data

body_frames:
  - frame_id: B1
    position: [0.0, 0.0, 0.0]    
    orientation: [0.0, 0.0, 0.0, 1.0] # quaternion (qx, qy, qz, qw)
    monitor_topic: "/B1_pose"
    box:
      name: sdf_box_1
      center: [0.120, -0.300, 0.050]    # [x, y, z] in metres (wrt frame B)
      orientation: [0.0, 0.0, 0.0, 1.0] # quaternion (qx, qy, qz, qw)
      size: [ 18, 18, 38 ]
  - frame_id: B2
    position: [0.0, 0.0, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0] # quaternion (qx, qy, qz, qw)
    monitor_topic: "/B2_pose"
    box:
      name: sdf_box_2
      center: [0.420,  0.170, 0.050]
      orientation: [0.0,   0.0,   0.0, 1.0]   
      size: [ 58, 58, 2 ]

      
Baselines:
  moveit_config_pkg: panda_moveit_config
  planner_ID: ['RRT', 'RRTConnect', 'RRTstar', 'PRM', 'LBKPIECE']


dh_type: "Modified"
dh_params:
  a:          [0.0, 0.0,    0.0,    0.0825, -0.0825, 0.0,   0.088, 0.0]
  alpha:      [0, -1.5708, 1.5708, 1.5708, -1.5708, 1.5708, 1.5708, 0.0]
  d:          [0.333, 0.0, 0.316, 0.0, 0.384, 0.0, 0.0, 0.107]
  theta_bias: [0, 0, 0, 0, 0, 0, 0, -0.7854]

  radii:
    [0.1,  0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05,
     0.05, 0.03, 0.05, 0.05, 0.05, 0.03, 0.03, 0.03,
     0.03, 0.03, 0.03, 0.03]

  frames:
    [0, 0, 1, 1, 2, 2, 2, 3, 3, 4,
     4, 4, 4, 6, 7, 7, 7, 7, 7, 7]

  centers:
    - [ 0.0,  0.0,  -0.3]
    - [ 0.0,  0.0,  -0.1]
    - [ 0.0,  0.0,  -0.07]
    - [ 0.0,  0.0,   0.07]
    - [ 0.0,  0.0,  -0.10]
    - [ 0.0,  0.0,  -0.175]
    - [ 0.0,  0.0,  -0.25]
    - [ 0.0,  0.0,  -0.05]
    - [ 0.0,  0.0,   0.05]
    - [ 0.0,  0.0,  -0.30]
    - [ 0.0,  0.08, -0.15]
    - [ 0.0,  0.10,  0.00]
    - [ 0.0,  0.00,  0.00]
    - [ 0.0,  0.0,  -0.05]
    - [ 0.0,  0.0,   0.00]
    - [ 0.0,  0.06,  0.00]
    - [ 0.0, -0.06,  0.00]
    - [ 0.0,  0.0,   0.04]
    - [ 0.0,  0.07,  0.04]
    - [ 0.0, -0.07,  0.04]